#AgeCalculetor
Birthday = int(input())
Age = 2026-Birthday
print(Age)

#Area of Square
side = int(input())
area = side*side
print(area)

#float functionTriel
Number = float(input())
N2 = float(input())
Sum = Number+N2
print(Sum)

print("Hello World!")

# Q. Take the name, age and height (in inches) of the students as input and print them.
name = input("Enter Your Name:")
age = int(input("Enter Your Age:"))
Height = float(input("Enter Your Height in inches:"))
print(".................................")
print (name,age,Height)
